In [1]:
import pennylane as qml
import pennylane.numpy as np
import gymnasium as gym
import stable_baselines3
from stable_baselines3 import PPO
from stable_baselines3 import DQN
from stable_baselines3.common.env_checker import check_env
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy
import matplotlib.pyplot as plt
!nvidia-smi

Thu Aug 15 16:27:19 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   55C    P3             14W /   36W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
def Cliff2():
    """
    Random 2-qubit Clifford circuit.

    Arguments:
        -nodes (np.ndarray): 
    
    Returns:
        -null
    """
    
    weights = np.random.randint(2, size=(2, 10))
    
    return qml.matrix(qml.RandomLayers(weights=weights,wires=[0,1])).numpy()

In [3]:
def RandomLayers(N_QUBITS, DEPTH):
    """
    Generates brick wall pattern of random 2 qubit Clifford gates

    Arguments:
        -N_QUBITS (int): Number of qubits
        -DEPTH (int): Depth of the circuit

    Returns:
        -random_layers (np.ndarray): Array of 4x4 unitaries (N_QUBITS, DEPTH, 4, 4)
    
    """

    random_layers = []
    for t in range(DEPTH):
        layer = []
        for x in range(0,N_QUBITS,2):
                layer.append(Cliff2())
        random_layers.append(layer)

    return random_layers


In [4]:
N_QUBITS = 2*2
DEPTH = 2

dev = qml.device("default.qubit", wires=N_QUBITS)

@qml.qnode(dev)
def circuit(theta, random_layers):
    """
    Quantum circuit with random entangling Clifford layers and disentangling layers.
    
    Arguments:
        -theta (np.ndarray): Binary matrix representing the positions of projections. (N_QUBITS, DEPTH)
    
    Returns:
        -Average Von Neumann entropy (float32): Average of 2-qubit Von Neumann entropies over all neighbors.
    """

    theta = theta.T
    DEPTH,N_QUBITS = np.shape(theta)

    for t in range(DEPTH):
        layer = random_layers[t]
        if t%2==0:
            for x in range(0,N_QUBITS,2):
                brick = layer[int(x/2)]
                qml.QubitUnitary(brick,wires=[x,x+1])
        elif t%2==1:
            for x in range(1,N_QUBITS-2,2):
                brick = layer[int((x-1)/2)]
                qml.QubitUnitary(brick,wires=[x,x+1])
            brick = layer[-1]
            qml.QubitUnitary(brick,wires=[N_QUBITS-1,0])
            
        projections = theta[t]
        for x in range(N_QUBITS):
            if projections[x]==1:
                qml.Projector(state=[0],wires=[x])
            
    entropies = []
    for x in range(N_QUBITS-1):
        entropies.append(qml.vn_entropy(wires=[x,x+1]))
    entropies.append(qml.vn_entropy(wires=[N_QUBITS-1,0]))
        
    return entropies

In [5]:
class Disentangler(gym.Env):
    """
    Reinforcement learning environment for the disentangler.
    """
    
    def __init__(self, n_qubits, depth, random_layers):
        super(Disentangler, self).__init__()
        
        self.N_QUBITS = n_qubits
        self.DEPTH = depth
        self.random_layers = random_layers
        self.alternating1 = alternating1 = np.array([(1+(-1)**x)%2 for x in range(N_QUBITS)])
        self.alternating2 = np.array([(2+(-1)**x)%2 for x in range(N_QUBITS)])

        self.action_space = gym.spaces.Discrete(self.N_QUBITS * self.DEPTH)
        self.observation_space = gym.spaces.Box(low=0, high=1, shape=(self.N_QUBITS, self.DEPTH), dtype=np.int8)
        self.state = np.zeros((self.N_QUBITS, self.DEPTH), dtype=np.int8)

    def step(self, action):
        # Initialize reward and done
        reward = 0
        done = False
        truncate = False

        # Apply the action
        h = np.zeros(self.N_QUBITS * self.DEPTH, dtype=np.int8)
        h[action] = 1
        h = h.reshape((self.N_QUBITS, self.DEPTH))
        self.state = (self.state + h) % 2

        # Calculate entropy (assumes circuit is a predefined function)
        entropies = circuit(self.state, self.random_layers)
        entropy = np.mean(entropies)

        # Check if the state is trivial
        trivial1 = (np.sum(self.state[:, -1]) == self.N_QUBITS)
        trivial2 = (np.sum(self.state[:, -1]) == self.N_QUBITS - 1)
        trivial3 = (self.state[:, -1] == self.alternating1)
        trivial4 = (self.state[:, -1] == self.alternating2)
        trivial = trivial1 or trivial2 or trivial3 or trivial4
        

        # Determine reward and done conditions
        if entropy < 1e-17:
            reward = 100
            done = True
        elif trivial:
            reward = -50
            done = True
            truncate = True
        
        # Return the state, reward, done flag, truncate flag, and info
        info = {}
        return self.state, reward, done, truncate, info
    
    def reset(self, seed=None):
        # Seed the random number generator if a seed is provided
        if seed is not None:
            np.random.seed(seed)
        
        # Reset the state to an all-zero matrix
        self.state = np.zeros((self.N_QUBITS, self.DEPTH), dtype=np.int8)

        info = {}
        return self.state, info
    
    def render(self):
        print()

    def close(self):
        # Optional: Implement any cleanup
        pass


In [6]:
ts = 1e5
lr = 0.001
ec = 0.01

env = Disentangler(n_qubits=N_QUBITS, depth=DEPTH, random_layers=RandomLayers(N_QUBITS, DEPTH))
env.reset()
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log="./tensorboard_files", learning_rate=lr, ent_coef=ec)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [7]:
model.learn(total_timesteps=ts, tb_log_name="{N_QUBITS}x{DEPTH}_tb_{ts}_{lr}_{ec}".format(N_QUBITS=N_QUBITS, DEPTH=DEPTH, ts=ts, lr=lr, ec=ec))
model_path = "./models/{N_QUBITS}x{DEPTH}_PPO_{ts}_{lr}_{ec}".format(N_QUBITS=N_QUBITS, DEPTH=DEPTH, ts=ts, lr=lr, ec=ec)
model.save(model_path)

Logging to ./tensorboard_files\4x3_tb_100000.0_0.001_0.01_3
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 7.21     |
|    ep_rew_mean     | -48.5    |
| time/              |          |
|    fps             | 179      |
|    iterations      | 1        |
|    time_elapsed    | 11       |
|    total_timesteps | 2048     |
---------------------------------
----------------------------------------
| rollout/                |            |
|    ep_len_mean          | 11.1       |
|    ep_rew_mean          | -50        |
| time/                   |            |
|    fps                  | 138        |
|    iterations           | 2          |
|    time_elapsed         | 29         |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.01852101 |
|    clip_fraction        | 0.223      |
|    clip_range           | 0.2        |
|    entropy_loss         | -2.47      |
|    explained_variance   

KeyboardInterrupt: 

In [8]:
model = PPO.load(model_path, env=env)

episodes = 10
optimal_measurements = []
for _ in range(episodes):
    obs, _ = env.reset()
    done = False
    
    while not done:
        action, _states = model.predict(obs)
        obs, rewards, done, truncate, info = env.step(action)

    optimal_measurements.append(obs)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [9]:
optimal_measurements

[tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=int8, requires_grad=True),
 tensor([[0, 0, 0],
         [0, 1, 0],
         [0, 1, 1],
         [0, 1, 0]], dtype=i

In [14]:
theta = optimal_measurements[0]
entropies_test = []
for _ in range(10):
    random_layers = RandomLayers(N_QUBITS,DEPTH)
    entropies_test.append(np.mean(circuit(theta, random_layers)))

entropies_test

[0.19463815861296896,
 7.609053996815012e-16,
 3.882395594258317e-16,
 9.940176752635207e-16,
 0.1608213264635111,
 1.895529643395682e-15,
 4.660561385372895e-15,
 2.2197156111778897e-15,
 0.09340892768898923,
 0.15654721352982132]